### ISSUE TITLE
low sec and Null sec chat window removed

### ISSUE THREAD

**Issue by Metalica** [EvEmu-Project/evemu_Crucible#120]
Adding option in server config to remove low sec and cull sec chat window removed.

**Comment by jdhirst** [comment]
This could theoretically be done, but since it would not match the game as it was during the Crucible expansion, it could not be enabled by default as this would deviate from expected functionality. As such, in order to focus development on current missing functionality, we cannot add this to the project board. 

Feel free to create a pull request with this change however to add a configuration option.
