### ISSUE TITLE
Seeded market orders do not show up

### ISSUE THREAD

**Issue by katz1** [EvEmu-Project/evemu_Crucible#134]
**Describe the bug**
I am trying to set up market seeding in my test environment, but no orders are showing up on the **Details** tab of the market window. I am fairly sure the seeding itself is activated, because on the **Groups** tab I can see prices now. See the attached screenshots for clarification.

**To Reproduce**
1. Set the SEED_MARKET=TRUE in the docker-compose.yml file
2. Build a new image
3. Dock at a station that supposed to be seeded, I checked in the DB that I had 10343 orders in station 60002956.
4. Check the orders of any item with any filter setting
5. No orders are showing up

**Expected behavior**
Orders should be visible at a stations that has orders according to the mktOrders table.

**Screenshots**
![market1](https://user-images.githubusercontent.com/18726138/132254801-7ea6727b-b86e-4d96-b2b3-6bf01623557a.jpg)
![market2](https://user-images.githubusercontent.com/18726138/132254810-7da14dd6-3fec-4a25-9c97-51dc0a18c73c.jpg)

**System Details:**
 - Server OS: Windows 10
 - Docker
 - Current master: 0f79bd138c727569924c19f8dcd6acaa5136a10f

**Comment by zhyrohaad** [comment]
something seems to be missing in the data sent to client.
enable market logs and post them here, pls.

**Comment by katz1** [comment]
Is this the data you meant? It is my first time looking at logs.
[mktDump.txt](https://github.com/EvEmu-Project/evemu_Crucible/files/7123641/mktDump.txt)

In the dumped data there is no order with station 60002956, but I assume that is because the dump is truncated after 100 orders? There is a buy order for item 2203 at station 60002956 in my DB.

**Comment by jdhirst** [comment]
@katz1 

Okay, so I have tested this now. I created a fresh Fedora 33 VM, installed docker and compose, downloaded the latest master commit, updated the compose file to enable seeding and ran `docker-compose -p evemu up -d`.

The server started fine, seemed to seed the database (took absolutely forever, but that is to be expected).

I connected a client, `.tr`'d to Jita and then opened the market. I now see what you are seeing, the groups are indeed populated, but the individual orders are not. 

The orders are indeed being found but the client seems to not receive anything. This is an example of an object sent to the client:
```
09:06:46 [MktDump]       [ 0]   [100] column_count=14
09:06:46 [MktDump]       [ 0]   [100]     [ 0] price:       Real: 283570.000000
09:06:46 [MktDump]       [ 0]   [100]     [ 1] volRemaining:    Integer: 550
09:06:46 [MktDump]       [ 0]   [100]     [ 2] typeID:    Integer: 607
09:06:46 [MktDump]       [ 0]   [100]     [ 3] range:    Integer: 0
09:06:46 [MktDump]       [ 0]   [100]     [ 4] orderID:    Integer: 4254973
09:06:46 [MktDump]       [ 0]   [100]     [ 5] volEntered:    Integer: 550
09:06:46 [MktDump]       [ 0]   [100]     [ 6] minVolume:    Integer: 1
09:06:46 [MktDump]       [ 0]   [100]     [ 7] bid:    Boolean: false
09:06:46 [MktDump]       [ 0]   [100]     [ 8] issueDate:       Long: 132478179209572976
09:06:46 [MktDump]       [ 0]   [100]     [ 9] duration:    Integer: 250
09:06:46 [MktDump]       [ 0]   [100]     [10] stationID:    Integer: 60000295
09:06:46 [MktDump]       [ 0]   [100]     [11] regionID:    Integer: 10000002
09:06:46 [MktDump]       [ 0]   [100]     [12] solarSystemID:    Integer: 30000130
09:06:46 [MktDump]       [ 0]   [100]     [13] jumps:    Integer: 1
```
Since type 607 is the Imicus, I reloaded the client/server, and then went to check that item manually to see what happens from the DB side. I also enabled general query logging on the db to see what is trying to be found.

The query is valid and is returning correct results:
```
SELECT    price, volRemaining, typeID, orderRange AS `range`, orderID,   volEntered, minVolume, bid, issued as issueDate, duration,   stationID, regionID, solarSystemID, jumps FROM mktOrders  WHERE regionID=10000002 AND typeID=607 AND bid=0;
```

Example of results:
```
+---------+--------------+--------+-------+---------+------------+-----------+-----+--------------------+----------+-----------+----------+---------------+-------+
| price   | volRemaining | typeID | range | orderID | volEntered | minVolume | bid | issueDate          | duration | stationID | regionID | solarSystemID | jumps |
+---------+--------------+--------+-------+---------+------------+-----------+-----+--------------------+----------+-----------+----------+---------------+-------+
|  763977 |          550 |    607 |     0 | 4254873 |        550 |         1 |     | 132478179209572976 |      250 |  60003241 | 10000002 |      30000163 |     1 |
|  476452 |          550 |    607 |     0 | 4254874 |        550 |         1 |     | 132478179209572976 |      250 |  60003049 | 10000002 |      30000161 |     1 |
```

What is even more interesting is that the client is definitely getting the orders to some degree because I am able to click the `Export to File` button and it does indeed produce valid data:

```
price,volRemaining,typeID,range,orderID,volEntered,minVolume,bid,issueDate,duration,stationID,regionID,solarSystemID,jumps,
271170.0,550,3359,0,4615580,550,1,False,2020-10-22 05:25:20.000,250,60000682,10000002,30000145,1,
271170.0,550,3359,0,4615611,550,1,False,2020-10-22 05:25:20.000,250,60003334,10000002,30000145,1,
...
```
Oh, I think I figured it out, they have expired. So I guess evedbtool needs to apply a new timestamp every time it runs instead of using the existing one. 

So to do this, I need to figure out the formatting of dates on the system. 

It turns out they have to be formatted as windows filetime for some reason (different epoch), so I had to implement that in evedbtool, but now when market is seeded, it uses the current timestamp as the order date.

After testing again, it works now. 😄 

![image](https://user-images.githubusercontent.com/9157196/132502267-d30bf6fd-19be-4ea4-b3f7-36eb1a5031f3.png)

Please fully re-build your DB and container (deleting all docker images and volumes associated with EVEmu), and it should now be fine.

**Comment by katz1** [comment]
@jdhirst 
Thanks for looking into this.
Unfortunately I already have some data in my DB I don't want to lose, so I didn't drop my DB volume.
I dropped everything else and cleared my mktOrders table, but the automatic seeding didn't work after rebuilding everything. Perhaps this is due to me not dropping my DB volume, I am not sure.
I also tried manually running `evedbtool seed` on the server container, which produced the following output:
````
sh-5.0# ./evedbtool seed
INFO[0000] EVEDBTool 0.0.4
INFO[0000] Seeding market...
INFO[0000] Seeding region Derelik
INFO[0000] 10000001
INFO[0000] Seeding region The Citadel
INFO[0000] 10000033
INFO[0000] Seeding region The Forge
INFO[0000] 10000002
INFO[0000] Executing migration...
INFO[0000] Successfully applied 0 migration!
````
It didn't seed my market though, my mktOrders table remained empty. I guess that `applied 0 migration` part is not correct?
In the end I just ran some queries manually that I found in `sql\seed_and_clean` with an updated timestamp, so my market is seeded now. But unfortunately I couldn't confirm if the EVEDBTool based seeding is working.

**Comment by jdhirst** [comment]
The tool checks to see if seeding was done before by updating a table in the db. That is why the db would have needed to be cleaned as the migration does not get triggered otherwise.

But I have verified that it works now for dbtool installations so I'll close this off.

**Comment by katz1** [comment]
I figured it out, I had to clean the `seed_migrations` table and then the tool applied the migration. Thanks again.
