### ISSUE TITLE
Skill Injection Intended Behavior?

### ISSUE THREAD

**Issue by TheOneJohiah** [EvEmu-Project/evemu_Crucible#183]
You can't inject a skillbook if the prerequisite skills haven't been completely trained.
Furthermore, there doesn't seem to be a check for prereqs when adding a skill with prereqs to the queue. Of course, this isn't currently an issue because you can't even inject the skill without having the prereqs already _trained_.

Is this placeholder functionality, or just how Crucible works?

**Comment by VizanArkonin** [comment]
Actually, that does sound like a plug too. It should work exactly the other way around - you can inject the skill even if prereqs are not completed, but you can't actually learn it until it's done. Pretty much one of the main reasons skill injection was added in a first place is to let people build a chain-queue without interrupting the learning process. It started working properly when queue was extended beyond 24h limit, but that's a whole different story :D

Now, this should be re-worked with caution - i remember we had funny reaction from client when we provided invalid SP counters on request (that notorious bug when you coulnd't use something even with all the skills trained up), so i'm wondering if that plug was put in because of that, or just as temp. solution until we get to refine it further.

**Comment by dawa11** [comment]
If my memory serves me right, you could not inject skills back then if the prerequisite weren‘t completed.

**Comment by VizanArkonin** [comment]
Nevemind, you're right :D
Did some more digging and found out that injecting with no prerequisites didn't arrive in crucible (2011) - it came around in [February 2016 with Skill Injectors](https://www.eveonline.com/news/view/patch-notes-for-february-2016-release). So right now it seems to work as intended.
